Riba meta doc  technical
Deltares/iMOD-Documentation pull request #66
Opened 2024-06-29 05:44 UTC by rleander

Ongoing work on a technical note on ribametamod, first stage draft

2024-07-02 12:35 UTC, HendrikKok requested changes

2024-07-02 12:35 UTC, HendrikKok commented on docs/coupler_ribametamod_technical.qmd
> +<li value=1> Surface water levels (stages) for all MODFLOW6 cells with an active RIV coupling to produce an estimate of the active RIV flux.
Could shortened to:

Exchange the Ribasim subgrid stage from the previous timestep to actively coupled RIV en DRN packages. 

I would drop all additional info on interpolation etc.

2024-07-02 12:35 UTC, HendrikKok commented on docs/coupler_ribametamod_technical.qmd
> +<b>Ribasim-MetaSWAP sub-timestepping</b>
align left again, now it looks like its a subprocess of exchange 2

2024-07-02 12:35 UTC, HendrikKok commented on docs/coupler_ribametamod_technical.qmd
> +<li value=4> Surface water sprinkling flux requested by MetaSWAP to be extracted from Ribasim, if allocated.</li>
Irrigation demand from MetaSWAP svats to Ribasim water users.

2024-07-02 12:35 UTC, HendrikKok commented on docs/coupler_ribametamod_technical.qmd
> +<li value=5> Surface water sprinkling flux realized by Ribasim, reported back to MetaSWAP</li>
Realized irrigation volume on SVATS based on realized volumes per water user. Potential shortage is proportionally distributed to SVATS based on there demands.

2024-07-02 12:35 UTC, HendrikKok commented on docs/coupler_ribametamod_technical.qmd
> +<li value=6> RIV flux, realized by Ribasim, reported back to MODFLOW6</li>
Compute correction-flux and exchange to MODFLOW 6 API-package  Correction arises in case that Ribasim basins can't realize (complete) infiltration demand.

2024-07-02 12:35 UTC, HendrikKok commented on docs/coupler_ribametamod_technical.qmd
> +<li value=7> Head of MODFLOW6 sent to MetaSWAP</li>
drop the sent?

2024-07-02 12:35 UTC, HendrikKok commented on docs/coupler_ribametamod_technical.qmd
> +* Flows directly to or from Ribasim are communicated to the Ribasim kernel via the BMI variables <b>infiltration</b> for all extractions from and <b>drainage</b> for all additions to Ribasim basin vo
I don't know what you want to say here?

2024-07-02 12:35 UTC, HendrikKok commented on docs/coupler_ribametamod_technical.qmd
> +
I think the some Remarks can de dropped. The information on specific exchange variables could be included above: so sprinkling demand to water user demands, sprinkling realized from water user realized.

2024-07-02 12:35 UTC, HendrikKok commented on docs/coupler_ribametamod_technical.qmd
> +### Active versus passive coupling
should be moved to preprocessor I think

2024-07-02 12:35 UTC, HendrikKok commented on docs/coupler_ribametamod_technical.qmd
> +communicated is communicated in entries of the user demand matrix.
double 'is communicated'

2024-07-02 12:35 UTC, HendrikKok commented on docs/coupler_ribametamod_technical.qmd
> +Mainly intended for checking, the coupler class now also supports logging of the values exchanged between components.
To get insight in the exchanged variables by the iMOD-coupler, the exchange values can be logged.

2024-07-02 12:35 UTC, HendrikKok commented on docs/coupler_ribametamod_technical.qmd
> +When performing an exchange, the ExchangeCollector instance is scanned
This part below does not give much additional info to the user I think.

2024-07-04 05:48 UTC, rleander commented on docs/coupler_ribametamod_technical.qmd
> +    loop Ribasim-MetaSWAP subtimesteps
done

2024-07-04 05:48 UTC, rleander commented on docs/coupler_ribametamod_technical.qmd
> +        Note over MetaSWAP: solve t
done

2024-07-04 05:48 UTC, rleander commented on docs/coupler_ribametamod_technical.qmd
> +<li value=1> Surface water levels (stages) for all MODFLOW6 cells with an active RIV coupling to produce an estimate of the active RIV flux.
done

2024-07-04 06:08 UTC, rleander commented on docs/coupler_ribametamod_technical.qmd
> +<b>Ribasim-MetaSWAP sub-timestepping</b>
done

2024-07-04 06:15 UTC, rleander commented on docs/coupler_ribametamod_technical.qmd
> +<li value=4> Surface water sprinkling flux requested by MetaSWAP to be extracted from Ribasim, if allocated.</li>
done

2024-07-04 06:18 UTC, rleander commented on docs/coupler_ribametamod_technical.qmd
> +<li value=5> Surface water sprinkling flux realized by Ribasim, reported back to MetaSWAP</li>
done

2024-07-04 06:34 UTC, rleander commented on docs/coupler_ribametamod_technical.qmd
> +<li value=7> Head of MODFLOW6 sent to MetaSWAP</li>
done

2024-07-04 06:49 UTC, rleander commented on docs/coupler_ribametamod_technical.qmd
> +<li value=6> RIV flux, realized by Ribasim, reported back to MODFLOW6</li>
done

2024-07-04 07:07 UTC, rleander commented on docs/coupler_ribametamod_technical.qmd
> +* Flows directly to or from Ribasim are communicated to the Ribasim kernel via the BMI variables <b>infiltration</b> for all extractions from and <b>drainage</b> for all additions to Ribasim basin vo
done

2024-07-04 07:08 UTC, rleander commented on docs/coupler_ribametamod_technical.qmd
> +* Flows directly to or from Ribasim are communicated to the Ribasim kernel via the BMI variables <b>infiltration</b> for all extractions from and <b>drainage</b> for all additions to Ribasim basin vo
removed point

2024-07-04 07:09 UTC, rleander commented on docs/coupler_ribametamod_technical.qmd
> +### Active versus passive coupling
done, removed

2024-07-04 07:29 UTC, rleander commented on docs/coupler_ribametamod_technical.qmd
> +communicated is communicated in entries of the user demand matrix.
done

2024-07-04 07:32 UTC, rleander commented on docs/coupler_ribametamod_technical.qmd
> +When performing an exchange, the ExchangeCollector instance is scanned
done

2024-07-04 09:02 UTC, rleander commented on docs/_quarto-website.yml
> +        - section: "Ribasim - MetaSWAP"
done

2024-07-05 11:06 UTC, HendrikKok approved these changes
Check your pre-commit + publish Website

2024-07-05 12:17 UTC, merged